---
swagger: '2.0'
info:
  version: '1.0'
  title: 'Bogo API'
# host: localhost:3000/api/v1/
host: bogo-staging.herokuapp.com/api/v1/
paths:
  authenticate:
    $ref: '/api/v1/authenticate.yml'
  password/forgot:
    $ref: '/api/v1/password/forgot.yml'
  password/reset:
    $ref: '/api/v1/password/reset.yml'
  clients/signup:
    $ref: '/api/v1/client/signup.yml'
  stylists/signup:
    $ref: '/api/v1/stylist/signup.yml'
  clients:
    $ref: '/api/v1/admin/clients.yml'
  stylists:
    $ref: '/api/v1/admin/stylists.yml'
  clients/{id}:
    $ref: '/api/v1/client/client_by_id.yml'
  stylists/{id}:
    $ref: '/api/v1/stylist/stylist_by_id.yml'
  stylists/nearest_stylists:
    $ref: '/api/v1/stylist/stylist_collection_actions.yml'
  services:
    $ref: '/api/v1/service/services.yml'
  services/{id}:
    $ref: '/api/v1/service/service_by_id.yml'
  services/nearest_services:
    $ref: '/api/v1/service/service_collection_actions.yml'
  service_types:
    $ref: '/api/v1/service_type/service_types.yml'
  service_types/{id}:
    $ref: '/api/v1/service_type/service_type_by_id.yml'
  schedules:
    $ref: '/api/v1/schedule/schedules.yml'
  schedules/{id}:
    $ref: '/api/v1/schedule/schedule_by_id.yml'
  availibilities:
    $ref: '/api/v1/availibility/availibilities.yml'
  availibilities/{id}:
    $ref: '/api/v1/schedule/availibility_by_id.yml'

securityDefinitions:
  JWT:
    description: "Token token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJyb2xlIjoiY2xpZW50IiwiZXhwIjoxNTY1ODEzMzY2fQ.3SNznryLiq9p2N9Ts28F6RaB-ae0pPKh75ZET6klkOY"
    type: string
    name: Authorization
    in: header
