---
swagger: '2.0'
info:
  version: '1.0'
  title: 'Bogo API'
# host: localhost:3000/api/v1/
# host: <%= Rails.application.secrets.secret_key_base %>
host: bogo-staging.herokuapp.com/api/v1/
paths:
  authenticate:
    $ref: '/api/v1/authenticate.yml'
  password/forgot:
    $ref: '/api/v1/password/forgot.yml'
  password/reset:
    $ref: '/api/v1/password/reset.yml'
  client/signup:
    $ref: '/api/v1/client/signup.yml'
  stylist/signup:
    $ref: '/api/v1/stylist/signup.yml'
  clients:
    $ref: '/api/v1/admin/clients.yml'
  stylists:
    $ref: '/api/v1/admin/stylists.yml'
  clients/{id}:
    $ref: '/api/v1/client/client_by_id.yml'
  stylists/{id}:
    $ref: '/api/v1/stylist/stylist_by_id.yml'
  stylists/nearest_stylists:
    $ref: '/api/v1/stylist/stylist_collection_actions.yml'
securityDefinitions:
  JWT:
    description: "Token token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJyb2xlIjoiY2xpZW50IiwiZXhwIjoxNTY1ODEzMzY2fQ.3SNznryLiq9p2N9Ts28F6RaB-ae0pPKh75ZET6klkOY"
    type: string
    name: Authorization
    in: header
