post:
  description: Create new service - [Admin, Stylist]
  tags:
    - Stylist
  parameters:
    - name: params
      in: body
      description: Service data
      schema:
        $ref: '#/components/schemas/Service'
get:
  description: Get all services - [Admin, Client, Stylist]
  tags:
    - Stylist
  parameters:
    - name: authorization
      in: header
      description: Admin authentication token
      required: true
      type: string
components:
  schemas:
    Service:
      type: object
      properties:
        name:
          type: string
        status:
          enum:
            - inactive
            - active
        service_type_id:
          type: integer
        stylist_id:
          type: integer
        amount:
          type: string
