development:
  secret_key_base: d707861c83672c3b74149c713e4fe750561015f958064872163ac926fb18423d18b2e40f11d40eb21dd27f1d25be853bf0cf7b1806ef98b48fb86381ee425451
  stripe_secret_key: sk_test_H7eILnSxDE4t6EvFq44XS2TE00ZNfcbovL
  admin_email: rafael.celiz@willdom.com
  sendgrid_username: app124685991@heroku.com
  sendgrid_password: z1kcvtvj4348
  fb_app_id: 2187588584874758
  fb_secret_key: 9e35ad79ddaf4acb1813d8ddffe83f26

test:
  secret_key_base: d707861c83672c3b74149c713e4fe750561015f958064872163ac926fb18423d18b2e40f11d40eb21dd27f1d25be853bf0cf7b1806ef98b48fb86381ee425451
  stripe_secret_key: sk_test_H7eILnSxDE4t6EvFq44XS2TE00ZNfcbovL
  admin_email: bogo@admin.com
  sendgrid_username: <%= ENV["SENDGRID_USERNAME"] %>
  sendgrid_password: <%= ENV["SENDGRID_PASSWORD"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_bucket_name: <%= ENV["AWS_BUCKET_NAME"] %>
  fb_app_id: <%= ENV["FB_APP_ID"] %>
  fb_secret_key: <%= ENV["FB_SECRET_KEY"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  host: <%= ENV["DOMAIN"] %>
  stripe_secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>
  admin_email: bogo@admin.com
  sendgrid_username: <%= ENV["SENDGRID_USERNAME"] %>
  sendgrid_password: <%= ENV["SENDGRID_PASSWORD"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_bucket_name: <%= ENV["AWS_BUCKET_NAME"] %>
  fb_app_id: <%= ENV["FB_APP_ID"] %>
  fb_secret_key: <%= ENV["FB_SECRET_KEY"] %>
